apiVersion: tekton.dev/v1beta1
kind: '{{default "Task" .Values.taskKind}}'
metadata:
  name: '{{default "ods" .Values.taskPrefix}}-build-go{{.Values.global.taskSuffix}}'
spec:
  description: |
    Builds Go (module) applications.

    The exact build recipe can be found at
    link:https://github.com/opendevstack/ods-pipeline/blob/master/build/package/scripts/build-go.sh[build/package/scripts/build-go.sh].

    The following provides an overview of the performed steps:

    - Source files are checked to be formatted with `gofmt`.
    - `golanci-lint` is run. The linter can be configured via a
      config file as described in the
      link:https://golangci-lint.run/usage/configuration/[configuration documentation].
    - Tests are executed. A potential `vendor` directory is excluded. Test
      results are converted into xUnit format. If test artifacts are already present for
      the current Git commit SHA, testing is skipped.
    - Application binary (named `app`) is built and placed into the directory
      specified by `output-dir`.

    Finally, the application source code is scanned by SonarQube.
    Default SonarQube project properties are provided unless `sonar-project.properties`
    is present.
    When `sonar-quality-gate` is set to `true`, the task will fail if the quality gate
    is not passed. If SonarQube is not desired, it can be disabled via `sonar-skip`.
    The SonarQube scan will include parameters to perform a pull request analysis if
    there is an open pull request for the branch being built. If the
    link:https://docs.sonarqube.org/latest/analysis/bitbucket-integration/[ALM integration]
    is setup properly, pull request decoration in Bitbucket is done automatically.

    The following artifacts are generated by the build task and placed into `.ods/artifacts/`

    * `code-coverage/`
      ** `coverage.out`
    * `lint-reports/`
      ** `report.txt`
    * `sonarqube-analysis/`
      ** `analysis-report.md`
      ** `issues-report.csv`
      ** `quality-gate.json`
    * `xunit-reports/`
      ** `report.xml`
  params:
    - name: working-dir
      description: |
        Working directory. The path must be relative to the root of the repository,
        without leading `./` and trailing `/`.
      type: string
      default: "."
    - name: enable-cgo
      description: Whether to enable CGO. When not enabled the build will set `CGO_ENABLED=0`.
      type: string
      default: "false"
    - name: go-os
      description: "`GOOS` variable (the execution operating system such as `linux`, `windows`)."
      type: string
      default: "linux"
    - name: go-arch
      description: "`GOARCH` variable (the execution architecture such as `arm`, `amd64`)."
      type: string
      default: "amd64"
    - name: output-dir
      description: >-
        Path to the directory into which the resulting Go binary should be copied, relative to `working-dir`.
        This directory may then later be used as Docker context for example.
      type: string
      default: docker
    - name: pre-test-script
      description: Script to execute before running tests, relative to the working directory.
      type: string
      default: ""
    - name: sonar-quality-gate
      description: Whether the SonarQube quality gate needs to pass for the task to succeed.
      type: string
      default: "false"
    - name: sonar-skip
      description: Whether to skip SonarQube analysis or not.
      type: string
      default: "false"
  steps:
    - name: build-go-binary
      # Image is built from build/package/Dockerfile.go-toolset.
      image: '{{.Values.registry}}/{{.Values.namespace}}/ods-go-toolset:{{.Values.global.imageTag}}'
      env:
        - name: HOME
          value: '/tekton/home'
        - name: CI
          value: "true"
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              key: debug
              name: ods-pipeline
      resources: {}
      script: |

        # build-go is build/package/scripts/build-go.sh.
        build-go \
          --working-dir=$(params.working-dir) \
          --enable-cgo=$(params.enable-cgo) \
          --go-os=$(params.go-os) \
          --go-arch=$(params.go-arch) \
          --pre-test-script=$(params.pre-test-script) \
          --output-dir=$(params.output-dir) \
          --debug=${DEBUG}
      workingDir: $(workspaces.source.path)
    - name: scan-with-sonar
      # Image is built from build/package/Dockerfile.sonar.
      image: '{{.Values.registry}}/{{.Values.namespace}}/ods-sonar:{{.Values.global.imageTag}}'
      env:
        - name: HOME
          value: '/tekton/home'
        - name: SONAR_URL
          valueFrom:
            configMapKeyRef:
              key: url
              name: ods-sonar
        - name: SONAR_EDITION
          valueFrom:
            configMapKeyRef:
              key: edition
              name: ods-sonar
        - name: SONAR_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: password
              name: ods-sonar-auth
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              key: debug
              name: ods-pipeline
      resources: {}
      script: |
        if [ "$(params.sonar-skip)" = "true" ]; then
          echo "Skipping SonarQube analysis"
        else
          mkdir -p .ods/artifacts/sonarqube-analysis
          # sonar is built from cmd/sonar/main.go.
          sonar \
            -working-dir=$(params.working-dir) \
            -quality-gate=$(params.sonar-quality-gate)
        fi
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
