apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pipeline-pvc
spec:
  storageClassName: "standard-nas-eco"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
