apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  tasks:
    - name: ods-start
      params:
        - name: submodules
          value: "true"
        - name: delete-existing
          value: "true"
        - name: verbose
          value: "true"
        - name: git-full-ref
          value: refs/heads/tekton
        - name: pipeline-run-name
          value: $(context.pipelineRun.name)
        - name: repository
          value: michael-go-helm
        - name: component
          value: go-helm
        - name: project
          value: michael
        - name: url
          value: "https://bitbucket.example.com/scm/example/example-app.git"
      taskRef:
        kind: ClusterTask
        name: ods-start-v0-1-0
      workspaces:
        - name: source
          workspace: pipeline-ws-source
    - name: ods-build-go
      runAfter:
        - ods-start
      taskRef:
        kind: ClusterTask
        name: ods-build-go-v0-1-0
      workspaces:
        - name: source
          workspace: pipeline-ws-source
    - name: ods-build-image
      runAfter:
        - ods-build-go
      taskRef:
        kind: ClusterTask
        name: ods-build-image-v0-1-0
      workspaces:
        - name: source
          workspace: pipeline-ws-source
    - name: ods-deploy-helm
      runAfter:
        - ods-build-image
      taskRef:
        kind: ClusterTask
        name: ods-deploy-helm-v0-1-0
      workspaces:
        - name: source
          workspace: pipeline-ws-source
  finally:
    - name: ods-finish
      params:
        - name: aggregate-tasks-status
          value: Succeeded
        - name: pipeline-run-name
          value: $(context.pipelineRun.name)
      taskRef:
        kind: ClusterTask
        name: ods-finish-v0-1-0
      workspaces:
        - name: source
          workspace: pipeline-ws-source
  workspaces:
    - name: pipeline-ws-source
