# Tasks
# Image tag to use for images referenced by tasks.
imageTag: 0.2.0
# Suffix to append to the task name.
taskSuffix: -v0-2-0

# Git
odsPipelineGitRepoUri: https://github.com/opendevstack/ods-pipeline
odsPipelineGitRepoRef: v0.2.0
