# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: image-registry.openshift-image-registry.svc:5000
namespace: ods
imageTag: 0.2.0
taskSuffix: ''
pushRegistry: image-registry.openshift-image-registry.svc:5000
