apiVersion: v1
kind: Secret
metadata:
  name: ods-aqua-auth
  labels:
    {{- include "chart.labels" . | nindent 4}}
stringData:
  password: '{{.Values.aquaPassword}}'
  username: '{{.Values.aquaUsername}}'
type: kubernetes.io/basic-auth
