apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" .}}
  labels:
    {{- include "chart.labels" . | nindent 4}}
spec:
  replicas: {{.Values.interceptor.replicaCount}}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8}}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-bitbucket.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret-bitbucket-auth.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{.Chart.Name}}
          securityContext: {}
          image: "{{.Values.interceptor.image.registry}}/{{.Values.interceptor.image.namespace | default .Release.Namespace}}/{{.Values.interceptor.image.repository | default .Chart.Name}}:{{.Values.interceptor.image.tag | default .Chart.AppVersion}}"
          imagePullPolicy: {{.Values.interceptor.image.pullPolicy}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: REPO_BASE
              valueFrom:
                configMapKeyRef:
                  key: repoBase
                  name: ods-bitbucket
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: password
                  name: ods-bitbucket-auth
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  key: debug
                  name: ods-pipeline
            - name: ODS_STORAGE_PROVISIONER
              value: '{{.Values.interceptor.storageProvisioner}}'
            - name: ODS_STORAGE_CLASS_NAME
              value: '{{.Values.interceptor.storageClassName}}'
            - name: ODS_STORAGE_SIZE
              value: '{{.Values.interceptor.storageSize}}'
            - name: ODS_PRUNE_MIN_KEEP_HOURS
              value: '{{int .Values.pipelineRunMinKeepHours}}'
            - name: ODS_PRUNE_MAX_KEEP_RUNS
              value: '{{int .Values.pipelineRunMaxKeepRuns}}'
          readinessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 20
            periodSeconds: 3
          resources:
            {{- toYaml .Values.interceptor.resources | nindent 12}}
      serviceAccountName: '{{.Values.serviceAccountName}}'
      serviceAccount: '{{.Values.serviceAccountName}}'
