apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ include "chart.fullname" . }}
  finalizers:
    - eventlisteners.triggers.tekton.dev
spec:
  podTemplate: {}
  serviceAccountName: '{{ .Values.serviceAccountName }}'
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: {{ include "chart.fullname" . }}
      interceptors:
        - bitbucket:
            secretRef:
              secretKey: password
              secretName: ods-bitbucket-webhook
        - webhook:
            objectRef:
              apiVersion: v1
              kind: Service
              name: {{ include "chart.fullname" . }}
              namespace: {{ .Release.Namespace }}
      name: {{ include "chart.fullname" . }}
      template:
        ref: {{ include "chart.fullname" . }}
