kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: '{{.Values.storageProvisioner}}'
  name: {{ include "chart.fullname" .}}
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: '{{.Values.storageClassName}}'
  volumeMode: Filesystem
