apiVersion: v1
kind: Secret
metadata:
  name: ods-nexus-auth
  labels:
    {{- include "chart.labels" . | nindent 4 }}
stringData:
  password: '{{ .Values.nexusPassword }}'
  username: '{{ .Values.nexusUsername }}'
type: kubernetes.io/basic-auth
