# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# General
serviceAccountName: 'pipeline'

# Bitbucket
bitbucketUrl: ''
bitbucketUsername: ''
bitbucketAccessToken: ''
bitbucketWebhookSecret: ''

# Nexus
nexusUrl: ''
nexusUsername: ''
nexusPassword: ''

# Sonar
sonarUrl: ''
sonarUsername: ''
sonarAuthToken: ''

# PVC
storageProvisioner: 'kubernetes.io/aws-ebs'
storageClassName: 'gp2'

# Cluster
consoleUrl: 'http://example.com'

# Webhook Interceptor
interceptor:
  apiHost: 'openshift.default.svc.cluster.local'
  replicaCount: 1
  image:
    registry: image-registry.openshift-image-registry.svc:5000
    # Overrides the image namespace whose default is the release namespace.
    namespace: ods
    # Overrides the image repository whose default is the chart name.
    repository: ods-webhook-interceptor
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    # tag: "0.1.0"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
