# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# General
serviceAccountName: 'pipeline'

# Bitbucket
# Bitbucket URL (including scheme). Example: https://bitbucket.example.com.
bitbucketUrl: ''
# Bitbucket username. Example: cd_user.
bitbucketUsername: ''
# Bitbucket personal access token (PAT) in clear text. This token needs to be
# created in Bitbucket for the user identified by "bitbucketUsername".
# The user requires write permissions in order to set build status or add code
# insights on commits.
bitbucketAccessToken: ''
# Shared secret between webhooks in Bitbucket and the event listener. Create
# a random secret and enter it here, then use it later on as the secret in any
# webhook you setup. The value needs to be in clear text.
bitbucketWebhookSecret: ''

# Nexus
# Nexus URL (including scheme). Example: https://nexus.example.com.
nexusUrl: ''
# Nexus username. Example: developer.
nexusUsername: ''
# Nexus password for the user identified by "nexusUsername" in clear text.
nexusPassword: ''
nexusTemporaryRepository: 'ods-temporary-artifacts'
nexusPermanentRepository: 'ods-permanent-artifacts'

# Sonar
# SonarQube URL (including scheme). Example: https://sonarqube.example.com.
sonarUrl: ''
# SonarQube username. Example: developer.
sonarUsername: ''
# SonarQube password for the user identified by "sonarUsername" in clear text.
sonarAuthToken: ''

# PVC
# Storage provisioner. On AWS backed clusters, use 'kubernetes.io/aws-ebs'.
storageProvisioner: 'kubernetes.io/aws-ebs'
# Storage class. On AWS backed clusters, use 'gp2'.
storageClassName: 'gp2'

# Cluster
# URL (including scheme) of the OpenShift Web Console.
consoleUrl: 'http://example.com'

# Webhook Interceptor
interceptor:
  # API host (no scheme) of the OpenShift/K8s API.
  apiHost: 'openshift.default.svc.cluster.local'
  # Number of replicas to run for the interceptor.
  replicaCount: 1
  image:
    # Image registry from which to pull the webhook interceptor container image.
    registry: image-registry.openshift-image-registry.svc:5000
    # Namespace from which to pull the webhook interceptor container image.
    # If not given, the image is pulled from the release namespace.
    namespace: ods
    # Repository (ImageStream) from which to pull the webhook interceptor
    # container image.
    # If not given, the image name equals the chart name.
    repository: ods-webhook-interceptor
    # Pull policy.
    pullPolicy: Always
    # Image tag to pull.
    # If not given, defaults to the chart appVersion.
    # tag: "0.1.0"
  # Deployment pod resources. Typically these settings should not need to change.
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
