apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: ods-build-go-v0-1-0
spec:
  description: ODS Build Go applications
  params:
    - default: "image-registry.openshift-image-registry.svc:5000/ods/ods-build-go:latest"
      description: The location of the Go builder image.
      name: go-image
      type: string
    - default: "false"
      description: Whether to enable CGO.
      name: enable-cgo
      type: string
    - default: ""
      description: GOOS variable.
      name: go-os
      type: string
    - default: ""
      description: GOARCH variable.
      name: go-arch
      type: string
    - default: "image-registry.openshift-image-registry.svc:5000/ods/ods-sonar:latest"
      description: The location of the Sonar image.
      name: sonar-image
      type: string
    - default: "false"
      description: Whether quality gate needs to pass.
      name: sonar-quality-gate
      type: string
    - default: "false"
      description: Whether to skip the SonarQube analysis or not.
      name: sonar-skip
      type: string
  steps:
    - # default image: build/package/Dockerfile.go-toolset
      image: $(params.go-image)
      name: build-go-binary
      resources: {}
      script: |

        # build-go is build/package/scripts/build-go.sh.
        build-go \
          --enable-cgo=$(params.enable-cgo) \
          --go-os=$(params.go-os) \
          --go-arch=$(params.go-arch)
      workingDir: $(workspaces.source.path)
    - # default image: build/package/Dockerfile.sonar
      image: $(params.sonar-image)
      name: scan-with-sonar
      env:
        - name: SONAR_URL
          valueFrom:
            configMapKeyRef:
              key: url
              name: ods-sonar
        - name: SONAR_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: password
              name: ods-sonar-auth
        - name: BITBUCKET_URL
          valueFrom:
            configMapKeyRef:
              key: url
              name: ods-bitbucket
        - name: BITBUCKET_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: password
              name: ods-bitbucket-auth
      resources: {}
      script: |
        if [ "$(params.sonar-skip)" = "true" ]; then
          echo "Skipping SonarQube analysis"
        else
          mkdir -p .ods/artifacts/sonarqube-analysis
          # sonar is built from cmd/sonar/main.go.
          sonar -quality-gate=$(params.sonar-quality-gate)
        fi
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
