kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ods-finish
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'ods-finish:{{.Values.global.imageTag}}'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  postCommit: {}
  strategy:
    type: Docker
  source:
    dockerfile: |-
      FROM ghcr.io/opendevstack/ods-pipeline/ods-finish:{{.Values.global.imageTag}}
  runPolicy: Serial
