{{if or .Values.global.enabledTasks.buildTypescript .Values.node16TypescriptToolset}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ods-node16-typescript-toolset
  annotations:
    "helm.sh/resource-policy": keep
{{end}}
