{{if or .Values.global.enabledTasks.buildGo .Values.goToolset}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ods-go-toolset
  annotations:
    "helm.sh/resource-policy": keep
{{end}}
