kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ods-java-toolset
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'ods-java-toolset:{{ .Values.imageTag }}'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: build/package/Dockerfile.java-toolset
      from:
        kind: DockerImage
        name: 'registry.redhat.io/ubi8'
      pullSecret:
        name: registry.redhat.io
  postCommit: {}
  source:
    type: Git
    git:
      uri: '{{ .Values.odsPipelineGitRepoUri }}'
      ref: '{{ .Values.odsPipelineGitRepoRef }}'
  runPolicy: Serial
