name: Tekton Tasks Tests

on: [push, pull_request]

jobs:
  openshift:
    name: OpenShift Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.1.2
        with:
          oc version: "v3.11.0"
          enable: "centos-imagestreams,persistent-volumes,registry,router"
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Interact with the cluster
        run: oc cluster status
      - name: Install Tekton on OpenShift
        run: |
          oc new-project tekton-pipelines --display-name='Tekton Pipelines'
          oc adm policy add-scc-to-user anyuid -z tekton-pipelines-controller
          oc apply --filename https://storage.googleapis.com/tekton-releases/latest/release.yaml
          oc rollout status deployment tekton-pipelines-controller -n tekton-pipelines
          oc rollout status deployment tekton-pipelines-webhook -n tekton-pipelines
      - name: Install Tekton CLI
        run: |
          curl -LO https://github.com/tektoncd/cli/releases/download/v0.18.0/tkn_0.18.0_Linux_x86_64.tar.gz
          sudo tar xvzf tkn_0.18.0_Linux_x86_64.tar.gz -C /usr/local/bin/ tkn
          tkn version
      - name: Create OpenShift resources
        run: |
          oc new-project ods --display-name='OpenDevStack'
          oc apply -f ./deploy -n ods
      - name: List Tekton resources
        run: |
          tkn clustertriggerbinding list
          tkn clustertask list
          tkn task list
