name: Tekton Tasks Tests

on: [push, pull_request]

jobs:
  openshift:
    name: OpenShift Cluster interaction
    runs-on: ubuntu-latest
    env:
      TKN_VERSION: "v0.23.0"
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Setup KinD
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.9.0"
          name: kind-ods-github-actions
          image: kindest/node:v1.19.1
      - name: Install Tekton Core Components
        run: kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/previous/${TKN_VERSION}/release.notags.yaml
      - name: Create OpenShift resources
        run: |
          kubectl apply -f ./scripts/task.yaml
          kubectl apply -f ./scripts/taskrun.yaml
      - name: List Tekton resources
        run: |
          kubectl get taskrun
      - name: Delete cluster
        if: always()
        run: |
          kind delete cluster kind-ods-github-actions
