name: Tekton Tasks Tests

on: [push, pull_request]

jobs:
  tekton-tests:
    name: K8s Cluster interaction
    runs-on: ubuntu-latest
    env:
      TKN_VERSION: "v0.22.0"
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup KinD cluster with internal registry
        working-directory: scripts
        run: ./kind-with-registry.sh

      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        id: install

      - name: Install Tekton Core Components
        run: kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/previous/${TKN_VERSION}/release.notags.yaml

      - name: Setup Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Run tests
        run: go test -v ./test/...
