name: Tekton Tasks Tests

on: [push, pull_request]

jobs:
  build-images:
    name: Build ODS images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image: ["buildah", "go-toolset", "helm", "interceptor", "sonar", "start"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
      -
        name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: build/package/Dockerfile.${{ matrix.image }}
          tags: localhost:5000/ods/${{ matrix.image }}:latest
          outputs: type=docker,dest=/tmp/image-${{ matrix.image }}.tar
      - 
        name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: buildx-image-${{ matrix.image }}
          path: /tmp/image-${{ matrix.image }}.tar
          retention-days: 1

  pipeline-tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: build-images
    env:
      TKN_VERSION: "v0.22.0"
    steps:
      - 
        name: Download buildah artifact
        uses: actions/download-artifact@v2
        with:
          path: /tmp/image-buildah.tar
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Setup KinD cluster with internal registry
        working-directory: scripts
        run: ./kind-with-registry.sh
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
      -
        name: Push buildah
        run: |
          docker load --input /tmp/image-buildah.tar
          docker push localhost:5000/ods/buildah:latest
      -
        name: Push go-toolset
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: build/package/Dockerfile.go-toolset
          tags: localhost:5000/ods/go-toolset:latest
          cache-from: type=local,src=/tmp/.buildx-cache-new
      -
        name: Push sonar
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: build/package/Dockerfile.sonar
          tags: localhost:5000/ods/sonar:latest
          cache-from: type=local,src=/tmp/.buildx-cache-new
      -
        name: Push start
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: build/package/Dockerfile.start
          tags: localhost:5000/ods/start:latest
          cache-from: type=local,src=/tmp/.buildx-cache-new
      -
        name: Setup kubectl
        uses: azure/setup-kubectl@v1
        id: install
      -
        name: Install Tekton Core Components
        run: kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/previous/${TKN_VERSION}/release.notags.yaml
      -
        name: Spin up Bitbucket container
        working-directory: scripts
        run: ./run-bitbucket.sh
      -
        name: Spin up Nexus container
        working-directory: scripts
        run: ./run-nexus.sh
      -
        name: Spin up SonarQube container
        working-directory: scripts
        run: ./run-sonarqube.sh
      -
        name: Setup Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Run tests
        run: go test -v ./test/... -always-keep-tmp-workspaces
