name: Publish Images

on:
  push:
    branches:
      - main
  pull_request:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_BASE: ${{ github.repository }}
  REF: ${{ github.event.pull_request.head.ref }}

jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image: ["buildah", "finish", "go-toolset", "gradle-toolset", "helm", "sonar", "start", "webhook-interceptor", "python-toolset", "node16-typescript-toolset"]
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate tag name
        run: |
          tag="latest"
          if [[ github_event_name != 'push' ]]; then
            tag="${github_ref_name//\//-}"
          fi
          echo "tag=$tag" >> $GITHUB_ENV
        env:
          github_event_name: ${{ github.event_name }}
          github_ref_name: ${{ env.REF }}

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.${{ matrix.image }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}/tst-${{ matrix.image }}:${{ env.tag }}

      # TODO:
      #   - on merging a PR to main: delete images tagged with PR's branch name
